version: '{build}'
image: Visual Studio 2022

build_script:
  - msbuild WinKill\WinKill.vcxproj /p:Configuration=Release /p:Platform=x64
  - '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com" WinKillSetup\WinKillSetup.vdproj /build Release'

artifacts:
  - path: WinKillSetup\Release\*.msi
    name: msi

deploy:
  - provider: GitHub
    release: 'WinKill v$(APPVEYOR_BUILD_VERSION)'
    description: 'Automated release from AppVeyor'
    auth_token: $(GH_PAT)
    artifact: WinKillSetup\Release\WinKill.msi
    draft: false
    prerelease: false
    on:
      branch: main
      APPVEYOR_REPO_TAG: true
