version: '{build}'
image: Visual Studio 2026

branches:
  only:
    - main

skip_tags: true

before_build:
  - ps: .\set-version.ps1

build_script:
  - msbuild WinKill\WinKill.vcxproj /p:Configuration=Release /p:Platform=x64
  - vsixinstaller.exe /quiet /admin /install "Microsoft.VisualStudio.InstallerProjects"
  - '"C:\Program Files\Microsoft Visual Studio\18\Community\Common7\IDE\devenv.com" WinKill.sln /rebuild "Release|Any CPU" /project WinKillSetup\WinKillSetup.vdproj /projectconfig "Release" /out "%APPVEYOR_BUILD_FOLDER%\build.log"'

artifacts:
  - path: WinKillSetup\Release\*.msi
    name: msi
  - path: WinKillSetup\Release\setup.exe
    name: setup

deploy:
  - provider: GitHub
    tag: $(RELEASE_TAG)
    release: 'WinKill $(RELEASE_TAG)'
    description: 'Automated release from AppVeyor'
    auth_token: $(GH_PAT)
    artifact: WinKillSetup\Release\WinKill.msi
    draft: false
    prerelease: false
    on:
      branch: main
