version: '{build}'
image: Visual Studio 2022

build_script:
  - msbuild WinKill\WinKill.vcxproj /p:Configuration=Release /p:Platform=x64
  - '"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com" WinKillSetup\WinKillSetup.vdproj /build Release'

artifacts:
  - path: WinKill\Release\*.msi
    name: msi
