version: '{build}'
image: Visual Studio 2022

build_script:
  - msbuild WinKill\WinKill.vcxproj /p:Configuration=Release /p:Platform=x64
  - msbuild WinKill\Winkill.vdproj /p:Configuration=Release

artifacts:
  - path: WinKill\Release\*.msi
    name: msi
